Router.configure({
  loadingTemplate: 'loading'
})

Router.map ->

  @route 'index', {
    path: '/'
    template: 'mainLayout'
    waitOn: ->
      Meteor.subscribe('schedules')
    action: ->
      if @ready()
        @render()
  }

  @route 'children', {
    layoutTemplate: 'innerLayout'
    waitOn: ->
      Meteor.subscribe('schedules')
    action: ->
      if @ready()
        @render()
  }

  @route 'teens', {
    layoutTemplate: 'innerLayout'
    waitOn: ->
      Meteor.subscribe('schedules')
    action: ->
      if @ready()
        @render()
  }

  @route 'lateteens', {
    layoutTemplate: 'innerLayout'
    waitOn: ->
      Meteor.subscribe('schedules')
    action: ->
      if @ready()
        @render()
  }

  @route 'news', {
    layoutTemplate: 'innerLayout'
    waitOn: ->
      Meteor.subscribe('auraPages')
    action: ->
      if @ready()
        @render()
  }

  @route 'grownups', {
    layoutTemplate: 'innerLayout'
    waitOn: ->
      Meteor.subscribe('schedules')
    action: ->
      if @ready()
        @render()
  }

  @route 'events', {
    layoutTemplate: 'innerLayout'
  }

  @route 'gallery', {
    path: 'gallery'
    layoutTemplate: 'innerLayout'
    template: 'gallery'

  }

  @route 'schedule', {
    layoutTemplate: 'innerLayout'
    waitOn: ->
      Meteor.subscribe('schedules')
    action: ->
      if @ready()
        @render()
  }

  @route 'contacts', {
    path: 'contacts'
    layoutTemplate: 'innerLayout'
    template: 'contacts'

  }

  @route 'blog', {
    path: 'blog'
    layoutTemplate: 'innerLayout'
    template: 'blog'

  }


# Generated by aura CLI

Router.onAfterAction ->

  document.body.scrollTop = 0
  Meteor.setTimeout ->
    if Session.get('admin.editMode') is true
      $('[contenteditable]').each ->
        $(this).attr('contenteditable', 'true')

  , 1000

#end